In [18]:
import pandas as pd

# Load dataset
df = pd.read_csv("../data/coaching_student_data.csv")

df.head()

        Name  English  Hindi  Maths  Science  Social Science  Computer
0     Saurya       51     60     50       64              55        71
1      Advik       80     90     66       74              91        68
2    Tanishi       75     82     74       81              84        90
3   Jaishree       75     64     90       75              84        60
4  Vaishnavi       84     72     84       86              49        84

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            14 non-null     str
 1   English         14 non-null     int64
 2   Hindi           14 non-null     int64
 3   Maths           14 non-null     int64
 4   Science         14 non-null     int64
 5   Social Science  14 non-null     int64
 6   Computer        14 non-null     int64
dtypes: int64(6), str(1)
memory usage: 916.0 bytes

In [20]:
#Clean column names

df.columns = df.columns.str.strip()

In [21]:
#Total Marks of students
df["Total"]=df.iloc[:,1:7].sum(axis=1)

In [22]:
#Percentage of students

df["Percentage"] = (df["Total"] / 600)*100

In [23]:
#Add Grade

def assign_grade(percentage):
    if percentage >= 90:
        return "A+"
    elif percentage >= 75:
        return "A"
    elif percentage >= 60:
        return "B"
    elif percentage >= 50:
        return "C"
    elif percentage >= 40:
        return "D"
    else:
        return "Fail"

df["Grade"] = df["Percentage"].apply(assign_grade)

In [24]:
#Saved cleaned dataset

df.to_csv("../data/coaching_student_cleaned.csv", index=False)

In [25]:
#Top Students

top_students = df.sort_values(by="Percentage", ascending=False).head(5)

top_students[["Name", "Percentage"]]

      Name  Percentage
13   Vivek   92.500000
12  Ritesh   92.500000
5    Aavya   88.500000
6   Shruti   87.166667
10   Tanvi   83.000000

In [26]:
#Weak students 

weak_students = df[df["Percentage"] < 40]
if weak_students.empty:
    print("No weak student in the class !")
else:
    print("Weak students")
    weak_students[["Name", "Percentage"]]

No weak student in the class !

In [34]:
#To fins weak subject of a studenst
subjects=["English", "Hindi", "Maths", "Science", "Social Science", "Computer"]
def find_weak_subjects(row):
    weak=[]
    for subject in subjects:
        if row[subject] < 40:
            weak.append(subject)
    if len (weak) == 0:
        return "No particular weak subject"
    return ", ".join(weak)

In [33]:
#Applying to dataset

df["Weak Subjects"] = df.apply(find_weak_subjects, axis=1)

In [29]:
#Subject wise Average marks in the class

subject_avg = df.iloc[:, 1:7].mean()

subject_avg

English           75.500000
Hindi             81.357143
Maths             83.428571
Science           80.500000
Social Science    80.857143
Computer          72.428571
dtype: float64

In [30]:
#Hardest subject

hardest_subject = subject_avg.idxmin()

In [31]:
#Teacher Insight

print("📌 Teacher Insight:")
print(f"Students are weak in {hardest_subject}")

📌 Teacher Insight:
Students are weak in Computer

In [35]:
#Students Needing Extra Attention

attention_students = df[df["Percentage"] < 60]

attention_students[["Name", "Percentage","Weak Subjects"]]

     Name  Percentage    Weak Subjects
0  Saurya        58.5  No weak subject

In [37]:
#Class Performance

print("📊 Class Summary")

print("Average Percentage of class:", df["Percentage"].mean())
print("Highest Score of class:", df["Percentage"].max())
print("Lowest Score of class:", df["Percentage"].min())

📊 Class Summary
Average Percentage of class: 79.01190476190477
Highest Score of class: 92.5
Lowest Score of class: 58.5

In [42]:
# Subject Weakness


subjects = ["English", "Hindi", "Maths", "Science", "Social Science", "Computer"]

weak_counts = {}

for sub in subjects:
    weak_counts[sub] = (df[sub] < 40).sum()

for sub , count in weak_counts.items():
    print(f"Weak in {sub}: {count} students ")

Weak in English: 0 students
Weak in Hindi: 0 students
Weak in Maths: 0 students
Weak in Science: 0 students
Weak in Social Science: 0 students
Weak in Computer: 0 students

In [44]:
# Subject-wise Performance

def categorize_student(percentage):
    if percentage >= 75:
        return "Good"
    elif percentage >= 50:
        return "Average"
    else:
        return "Weak"

df["Category"] = df["Percentage"].apply(categorize_student)

df[["Name", "Percentage", "Category"]]

          Name  Percentage Category
0       Saurya   58.500000  Average
1        Advik   78.166667     Good
2      Tanishi   81.000000     Good
3     Jaishree   74.666667  Average
4    Vaishnavi   76.500000     Good
5        Aavya   88.500000     Good
6       Shruti   87.166667     Good
7        Kirti   70.166667  Average
8   Deevyanshu   77.833333     Good
9        Mansi   81.166667     Good
10       Tanvi   83.000000     Good
11     Kritika   64.500000  Average
12      Ritesh   92.500000     Good
13       Vivek   92.500000     Good

In [48]:
#Weak Subject of students

subjects = ["English", "Hindi", "Maths", "Science", "Social Science", "Computer"]

def get_weak_subjects(row):
    weak = []
    for sub in subjects:
        if row[sub] < 40:
            weak.append(sub)
        if len(weak) == 0:
            return "No weak subject"
    return ", ".join(weak)
    
df["Weak Subjects"] = df.apply(get_weak_subjects, axis=1)

df[["Name", "Weak Subjects"]]

          Name    Weak Subjects
0       Saurya  No weak subject
1        Advik  No weak subject
2      Tanishi  No weak subject
3     Jaishree  No weak subject
4    Vaishnavi  No weak subject
5        Aavya  No weak subject
6       Shruti  No weak subject
7        Kirti  No weak subject
8   Deevyanshu  No weak subject
9        Mansi  No weak subject
10       Tanvi  No weak subject
11     Kritika  No weak subject
12      Ritesh  No weak subject
13       Vivek  No weak subject

In [50]:
#Strong subject of students

def get_strong_subjects(row):
    strong = []
    for sub in subjects:
        if row[sub] >= 75:
            strong.append(sub)
        if len(strong) == 0:
            return "No particular strong subject"
    return ", ".join(strong)

df["Strong Subjects"] = df.apply(get_strong_subjects, axis=1)

df[["Name", "Strong Subjects"]]

          Name                                    Strong Subjects
0       Saurya                       No particular strong subject
1        Advik                     English, Hindi, Social Science
2      Tanishi  English, Hindi, Science, Social Science, Computer
3     Jaishree            English, Maths, Science, Social Science
4    Vaishnavi                  English, Maths, Science, Computer
5        Aavya     English, Hindi, Maths, Science, Social Science
6       Shruti                       No particular strong subject
7        Kirti                       No particular strong subject
8   Deevyanshu                       No particular strong subject
9        Mansi              English, Hindi, Maths, Social Science
10       Tanvi                       No particular strong subject
11     Kritika                                     English, Maths
12      Ritesh  English, Hindi, Maths, Science, Social Science...
13       Vivek  English, Hindi, Maths, Science, Social Science...

In [52]:
#Student Performance 

def performance_type(row):
    if row["Category"] == "Strong" and row["Weak Subjects"] != "":
        return "Strong but Weak in Some Subjects"
    elif row["Category"] == "Weak" and row["Strong Subjects"] != "":
        return "Weak but Good in Some Subjects"
    else:
        return "Consistent Performance"

df["Performance Type"] = df.apply(performance_type, axis=1)

df[["Name", "Category", "Performance Type"]]

          Name Category        Performance Type
0       Saurya  Average  Consistent Performance
1        Advik     Good  Consistent Performance
2      Tanishi     Good  Consistent Performance
3     Jaishree  Average  Consistent Performance
4    Vaishnavi     Good  Consistent Performance
5        Aavya     Good  Consistent Performance
6       Shruti     Good  Consistent Performance
7        Kirti  Average  Consistent Performance
8   Deevyanshu     Good  Consistent Performance
9        Mansi     Good  Consistent Performance
10       Tanvi     Good  Consistent Performance
11     Kritika  Average  Consistent Performance
12      Ritesh     Good  Consistent Performance
13       Vivek     Good  Consistent Performance

In [53]:
df.to_csv("../data/coaching_student_final.csv", index=False)

In [ ]:
#Adding Recommendations

def generate_recommendation(row):
    
    weak = row["Weak Subjects"]
    strong = row["Strong Subjects"]

    # STRONG STUDENTS
    if row["Category"] == "Strong":
        if weak and weak != "No weak subject":
            return f"Strong overall, but needs improvement in {weak}"
        else:
            return "Excellent performance. Keep it up!"
    
    # AVERAGE STUDENTS
    elif row["Category"] == "Average":
        if weak and weak != "No weak subject":
            return f"Can improve. Focus on {weak}"
        else:
            return "Good performance. Try to reach strong category."
    
    # WEAK STUDENTS
    else:
        if strong and strong != "":
            return f"Needs improvement overall, but doing well in {strong}"
        else:
            return "Needs serious improvement in all subjects"

In [61]:
#Applying recommendations to dataset

df["Recommendation"] = df.apply(generate_recommendation, axis=1)

df[["Name", "Recommendation"]]

          Name                                     Recommendation
0       Saurya    Good performance. Try to reach strong category.
1        Advik  Needs improvement overall, but doing well in E...
2      Tanishi  Needs improvement overall, but doing well in E...
3     Jaishree    Good performance. Try to reach strong category.
4    Vaishnavi  Needs improvement overall, but doing well in E...
5        Aavya  Needs improvement overall, but doing well in E...
6       Shruti  Needs improvement overall, but doing well in N...
7        Kirti    Good performance. Try to reach strong category.
8   Deevyanshu  Needs improvement overall, but doing well in N...
9        Mansi  Needs improvement overall, but doing well in E...
10       Tanvi  Needs improvement overall, but doing well in N...
11     Kritika    Good performance. Try to reach strong category.
12      Ritesh  Needs improvement overall, but doing well in E...
13       Vivek  Needs improvement overall, but doing well in E...

In [63]:
df.to_csv("../data/coaching_student_final.csv", index=False)